# Generated by Django 5.0.6 on 2024-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('likelihood', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('topics', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
