# Generated by Django 5.0.6 on 2024-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='topics',
            field=models.CharField(max_length=250),
        ),
    ]
