# Generated by Django 5.0.6 on 2024-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_remove_data_city_remove_data_topics_remove_data_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
