# Generated by Django 5.0.6 on 2024-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_alter_data_added_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank='True'),
        ),
    ]
