# Generated by Django 5.0.6 on 2024-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_alter_data_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
