# Generated by Django 5.0.6 on 2024-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_alter_data_region_alter_data_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
