# Generated by Django 5.0.6 on 2024-06-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0009_alter_data_sector_alter_data_topic_alter_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='insight',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
