# Generated by Django 5.0.6 on 2024-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0010_alter_data_country_alter_data_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
